config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'products#index'
  resources :products
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/color.rb
# frozen_string_literal: true

class Color < ApplicationRecord
  has_many :combinations

  validates :name, presence: true
end

app/models/combination.rb
class Combination < ApplicationRecord
  belongs_to :product
  belongs_to :color
  belongs_to :size

  validates :amount, presence: true
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  has_one :combination, dependent: :destroy

  accepts_nested_attributes_for :combination

  validates :name, presence: true
  validates :description, presence: true
end

app/models/size.rb
# frozen_string_literal: true

class Size < ApplicationRecord
  has_many :combinations

  validates :name, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
    @product.build_combination
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      flash[:notice] = "Produto Criado com sucesso"
      redirect_to @product
    else
      render :new
    end
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      flash[:notice] = "Produto Atualizado com sucesso"
      redirect_to @product
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])

    @product.destroy
    flash[:notice] = "Produto Deletado com sucesso"
    redirect_to products_url
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit :name, :description, combination_attributes: [:id, :amount, :color_id, :size_id]
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  include Shared::FlashHelper
end

app/helpers/product_helper.rb
module ProductHelper
  def template_links(object, action_name)
    send("#{action_name}_links", object) rescue ArgumentError.new("Should have created a method for action #{action_name}")
  end

  private

  def index_links(object)
    capture do
      concat link_to 'Show', product_path(object), class: "btn btn-primary mr-1", style: "color: #fff"
      concat link_to 'Edit', edit_product_path(object), class: "btn btn-info mr-1", style: "color: #fff"
      concat link_to 'Destroy', product_path(object), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger mr-1", style: "color: #fff"
    end
  end

  def show_links(object)
    capture do
      concat link_to 'Edit', edit_product_path(object), class: "btn btn-primary mr-1", style: "color: #fff"
      concat link_to 'Back', products_path, class: "btn btn-info mr-1", style: "color: #fff"
    end
  end
end

app/helpers/shared/flash_helper.rb
module Shared::FlashHelper
  def flash_message
    messages = ""
    [:notice, :info, :warning, :error].each do |type|
      if flash[type]
        messages += content_tag(:div, flash[type], class: "alert alert-info")
      end
    end

    messages.html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CadProduct</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application'  %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= flash_message %>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= simple_form_for product do |f| %>
  <%= f.error_notification %>

  <%= f.input :name %>
  <%= f.input :description %>

  <%= f.simple_fields_for :combination do |ff| %>
    <%= ff.association :color %>
    <%= ff.association :size %>
    <%= ff.input :amount %>
  <% end %>

  <%= f.button :submit, class: "btn-primary" %>
  <%= link_to 'Cancelar', products_path, class: "btn btn-warning", style: "color: #fff" %>
<% end %>

app/views/products/_product.html.erb
<div class="card mb-4 shadow-sm">
  <div class="card-header">
    <h4 class="my-0 font-weight-normal"><%= product.name %></h4>
  </div>
  <div class="card-body">
    <h1 class="card-title pricing-card-title"><strong>Quantidade: </strong><%=product&.combination&.amount%></h1>
    <ul class="list-unstyled mt-3 mb-4">
      <li><strong>Decrição: </strong><%= product.description %></li>
      <li><strong>Tamanho: </strong><%= product&.combination&.size&.name %></li>
      <li><strong>Cor: </strong><%= product&.combination&.color&.name %></li>
    </ul>
    <%= template_links(product, action_name) %>
  </div>
</div>

app/views/products/edit.html.erb
<div class="container">
  <div class="row">
    <%= render 'form', product: @product  %>
  </div>
</div>

app/views/products/index.html.erb
<div class="container">
  <h1>Estoque</h1>
  <div class="card-deck mb-3 text-center">
    <% if @products.present? %>
      <% @products.each do |product| %>
        <%= render 'product', product: product %>
      <% end %>
    <% end %>
  </div>
</div>
<div class="container">
  <%= link_to 'Cadastrar novo produto', new_product_path, class: "btn btn-lg btn-block btn-primary", style: "color: #fff" %>
</div>

app/views/products/new.html.erb
<div class="container">
  <div class="row">
    <%= render 'form', product: @product  %>
  </div>
</div>

app/views/products/show.html.erb
<div class="container">
  <div class="row">
    <%= render 'product', product: @product %>
  </div>
</div>